// todo: review them and remove the unnecessary ones
export const categories = {
  expenses: [
    "Beauty",
    "Bills & Fees",
    "Car",
    "Education",
    "Entertainment",
    "Family & Personal",
    "Food & Drink",
    "Gifts",
    "Groceries",
    "Healthcare",
    "Home",
    "Shopping",
    "Sport & Hobby",
    "Transport",
    "Travel",
    "Work",
  ],
  income: [
    "Business",
    "Extra Income",
    "Gifts",
    "Insurance Payout",
    "Loan",
    "Other",
    "Parental Leave",
    "Salary",
  ],
  additionalExpenses: [
    "Pets",
    "Utilities",
    "Rent",
    "Mortgage",
    "Personal Care",
    "Subscriptions",
    "Taxes",
    "Childcare",
    "Donations",
    "Electronics",
    "Home Repair",
    "Furnishings",
    "Gardening",
    "Legal Fees",
    "Stationery",
    "Laundry",
    "Fitness",
  ],
  additionalIncome: [
    "Rental Income",
    "Dividends",
    "Investment Returns",
    "Royalties",
    "Freelancing",
    "Child Support",
    "Alimony",
    "Pension",
    "Social Security",
    "Unemployment Benefits",
    "Reimbursements",
    "Scholarships",
    "Grants",
    "Lottery Winnings",
    "Side Business",
    "Interest Income",
  ],
};
